# Generated by Django 2.1.3 on 2018-11-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aempresa_depoimentos_oquebitcoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('menu_name', models.CharField(max_length=50)),
                ('order', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
