# Generated by Django 2.1.3 on 2018-11-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_onepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AEmpresa',
        ),
        migrations.DeleteModel(
            name='Depoimentos',
        ),
        migrations.DeleteModel(
            name='Missao',
        ),
        migrations.DeleteModel(
            name='OqueBitcoin',
        ),
        migrations.AddField(
            model_name='onepage',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
    ]
